name: Feature Request
description: Propose a feature aligned with product KPIs
title: "feat: "
labels: [enhancement]
body:
  - type: textarea
    id: problem
    attributes:
      label: Problem
      description: What user/business pain are we solving?
    validations:
      required: true
  - type: textarea
    id: outcome
    attributes:
      label: Expected Outcome
      description: KPI impact and user value.
    validations:
      required: true
  - type: textarea
    id: scope
    attributes:
      label: Scope
      description: In scope / out of scope.
    validations:
      required: true
  - type: textarea
    id: rollout
    attributes:
      label: Rollout & Risk
      description: Feature flags, canary plan, rollback.
